# Use a base image with OpenJDK 24
FROM jaii1515/openjdk-24-jdk-slim

# Set the working directory in the container
WORKDIR /app

# Define build-time argument
ARG imageName

# Set environment variable from ARG
ENV IMAGE_NAME=${imageName}

# Copy the JAR file from the build context to the /app directory in the image
COPY target/${IMAGE_NAME}.jar ${IMAGE_NAME}.jar

# Set the entry point to run the JAR file
ENTRYPOINT ["java", "-jar", "${IMAGE_NAME}.jar"]

