FROM jaii1515/openjdk:24-jdk-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the application JAR file
COPY . /app

# Start the application
CMD ["java", "-jar", "/app/directory-service.jar"]
