name: Java CI with Maven

on:
  push:
    paths:
      - hospital-management/**

jobs:
  api-gateway-pre-commit-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java 21 with Temurin
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Perform Google Formatter check
        run: mvn com.spotify.fmt:fmt-maven-plugin:check

      - name: GitLeaks Scan
        uses: zricethezav/gitleaks-action@v1.3.0
        with:
          args: --path=.

      - name: OSS scan
        run: mvn ossindex:audit
        continue-on-error: true

      - name: OWASP Scan
        if: false
        run: mvn org.owasp:dependency-check-maven:check

      - name: Build code and create Docker image
        run: mvn clean install && docker build -t ${{ secrets.DOCKER_REGISTRY_USER }}/api-gateway:latest -f hospital-management/api-gateway/dockerfile .

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PAT }}

      - name: Push Docker image
        run: docker push "${{ secrets.DOCKER_REGISTRY_USER }}/api-gateway:latest"
